<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $clients = [
            [
                'nom' => 'Dipama',
                'prenom' => 'Jean-Baptiste',
                'telephone' => '+22670111111',
                'email' => 'jb.dipama@gmail.com',
                'date_naissance' => '1985-03-15',
                'adresse' => 'Secteur 15, Ouaga 2000',
                'date_premiere_visite' => now()->subMonths(8),
                'date_derniere_visite' => now()->subDays(5),
                'points_fidelite' => 250,
                'montant_total_depense' => 185000,
                'notes' => 'Préfère les coupes classiques. Client régulier.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(8),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Sankara',
                'prenom' => 'Marie',
                'telephone' => '+22670222222',
                'email' => 'marie.sankara@yahoo.fr',
                'date_naissance' => '1992-07-22',
                'adresse' => 'Zone du Bois, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(12),
                'date_derniere_visite' => now()->subDays(15),
                'points_fidelite' => 480,
                'montant_total_depense' => 325000,
                'notes' => 'Aime les tresses africaines. Allergique aux colorations chimiques.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(12),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Yameogo',
                'prenom' => 'Paul',
                'telephone' => '+22670333333',
                'email' => null,
                'date_naissance' => '1978-11-05',
                'adresse' => 'Patte d\'Oie, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(18),
                'date_derniere_visite' => now()->subDays(7),
                'points_fidelite' => 820,
                'montant_total_depense' => 567000,
                'notes' => 'Client VIP. Vient tous les samedis matin. Préfère Ibrahim comme coiffeur.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(18),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Kindo',
                'prenom' => 'Rachelle',
                'telephone' => '+22670444444',
                'email' => 'rachelle.kindo@outlook.com',
                'date_naissance' => '1995-09-18',
                'adresse' => 'Gounghin, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(4),
                'date_derniere_visite' => now()->subDays(2),
                'points_fidelite' => 150,
                'montant_total_depense' => 98000,
                'notes' => 'Préfère les coiffures modernes et les extensions.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(4),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Ouattara',
                'prenom' => 'Boukary',
                'telephone' => '+22670555555',
                'email' => 'b.ouattara@hotmail.com',
                'date_naissance' => '1988-01-30',
                'adresse' => 'Tanghin, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(24),
                'date_derniere_visite' => now()->subDays(3),
                'points_fidelite' => 1200,
                'montant_total_depense' => 875000,
                'notes' => 'Client fidèle depuis 2 ans. Achète régulièrement des produits.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(24),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Ilboudo',
                'prenom' => 'Salimata',
                'telephone' => '+22670666666',
                'email' => null,
                'date_naissance' => '1990-05-12',
                'adresse' => 'Cissin, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(6),
                'date_derniere_visite' => now()->subDays(20),
                'points_fidelite' => 180,
                'montant_total_depense' => 124000,
                'notes' => 'Préfère Fatima pour les coiffures féminines.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(6),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Bamogo',
                'prenom' => 'Richard',
                'telephone' => '+22670777777',
                'email' => 'richard.bamogo@gmail.com',
                'date_naissance' => '1982-12-25',
                'adresse' => 'Dapoya, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(10),
                'date_derniere_visite' => now()->subDays(1),
                'points_fidelite' => 340,
                'montant_total_depense' => 235000,
                'notes' => 'Barbe complète chaque semaine. Très ponctuel.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(10),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tapsoba',
                'prenom' => 'Clarisse',
                'telephone' => '+22670888888',
                'email' => 'clarisse.tapsoba@yahoo.fr',
                'date_naissance' => '1993-08-07',
                'adresse' => 'Somgandé, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(3),
                'date_derniere_visite' => now()->subDays(12),
                'points_fidelite' => 95,
                'montant_total_depense' => 67500,
                'notes' => 'Nouvelle cliente. Aime essayer différents styles.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(3),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Nakoulma',
                'prenom' => 'Hamidou',
                'telephone' => '+22670999999',
                'email' => 'hamidou.nakoulma@outlook.com',
                'date_naissance' => '1987-04-19',
                'adresse' => 'Tampouy, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(15),
                'date_derniere_visite' => now()->subDays(8),
                'points_fidelite' => 620,
                'montant_total_depense' => 445000,
                'notes' => 'Client satisfait. Recommande souvent le salon.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(15),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Zida',
                'prenom' => 'Adama',
                'telephone' => '+22671000000',
                'email' => null,
                'date_naissance' => '1999-02-14',
                'adresse' => 'Kossodo, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(2),
                'date_derniere_visite' => now()->subDays(25),
                'points_fidelite' => 45,
                'montant_total_depense' => 32000,
                'notes' => 'Étudiant. Préfère les coupes tendance.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(2),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Somé',
                'prenom' => 'Élisabeth',
                'telephone' => '+22671111111',
                'email' => 'elisa.some@gmail.com',
                'date_naissance' => '1991-06-28',
                'adresse' => 'Dassasgho, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(20),
                'date_derniere_visite' => now()->subDays(4),
                'points_fidelite' => 950,
                'montant_total_depense' => 678000,
                'notes' => 'Cliente fidèle. Aime les tissages et colorations.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(20),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Yaméogo',
                'prenom' => 'Christophe',
                'telephone' => '+22671222222',
                'email' => 'chris.yameogo@hotmail.com',
                'date_naissance' => '1980-10-03',
                'adresse' => 'Bogodogo, Ouagadougou',
                'date_premiere_visite' => now()->subMonths(5),
                'date_derniere_visite' => now()->subDays(30),
                'points_fidelite' => 120,
                'montant_total_depense' => 85000,
                'notes' => 'Vient irrégulièrement.',
                'is_active' => true,
                'sync_status' => 'synced',
                'created_at' => now()->subMonths(5),
                'updated_at' => now(),
            ],
        ];

        DB::table('clients')->insert($clients);
    }
}