<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MouvementStockSeeder extends Seeder
{
    public function run(): void
    {
        $mouvements = [
            // Entrées de stock initiales (inventaire)
            [
                'produit_id' => 1,
                'type_mouvement' => 'inventaire',
                'quantite' => 25,
                'stock_avant' => 0,
                'stock_apres' => 25,
                'motif' => 'Stock initial - inventaire de démarrage',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'produit_id' => 2,
                'type_mouvement' => 'inventaire',
                'quantite' => 40,
                'stock_avant' => 0,
                'stock_apres' => 40,
                'motif' => 'Stock initial - inventaire de démarrage',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'produit_id' => 3,
                'type_mouvement' => 'inventaire',
                'quantite' => 18,
                'stock_avant' => 0,
                'stock_apres' => 18,
                'motif' => 'Stock initial - inventaire de démarrage',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'produit_id' => 6,
                'type_mouvement' => 'inventaire',
                'quantite' => 50,
                'stock_avant' => 0,
                'stock_apres' => 50,
                'motif' => 'Stock initial - inventaire de démarrage',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'produit_id' => 8,
                'type_mouvement' => 'inventaire',
                'quantite' => 28,
                'stock_avant' => 0,
                'stock_apres' => 28,
                'motif' => 'Stock initial - inventaire de démarrage',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'produit_id' => 9,
                'type_mouvement' => 'inventaire',
                'quantite' => 35,
                'stock_avant' => 0,
                'stock_apres' => 35,
                'motif' => 'Stock initial - inventaire de démarrage',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            
            // Sorties liées aux ventes
            [
                'produit_id' => 1,
                'type_mouvement' => 'sortie',
                'quantite' => -1,
                'stock_avant' => 25,
                'stock_apres' => 24,
                'motif' => 'Vente à Jean-Baptiste Dipama',
                'vente_id' => 1,
                'user_id' => 3,
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'produit_id' => 6,
                'type_mouvement' => 'sortie',
                'quantite' => -1,
                'stock_avant' => 50,
                'stock_apres' => 49,
                'motif' => 'Vente à Jean-Baptiste Dipama',
                'vente_id' => 1,
                'user_id' => 3,
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'produit_id' => 8,
                'type_mouvement' => 'sortie',
                'quantite' => -1,
                'stock_avant' => 28,
                'stock_apres' => 27,
                'motif' => 'Vente à Paul Yameogo',
                'vente_id' => 3,
                'user_id' => 3,
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'produit_id' => 3,
                'type_mouvement' => 'sortie',
                'quantite' => -1,
                'stock_avant' => 18,
                'stock_apres' => 17,
                'motif' => 'Vente à Paul Yameogo',
                'vente_id' => 3,
                'user_id' => 3,
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'produit_id' => 2,
                'type_mouvement' => 'sortie',
                'quantite' => -2,
                'stock_avant' => 40,
                'stock_apres' => 38,
                'motif' => 'Vente à Boukary Ouattara',
                'vente_id' => 4,
                'user_id' => 2,
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'produit_id' => 9,
                'type_mouvement' => 'sortie',
                'quantite' => -1,
                'stock_avant' => 35,
                'stock_apres' => 34,
                'motif' => 'Vente à Richard Bamogo',
                'vente_id' => 6,
                'user_id' => 5,
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            
            // Entrées de stock (réapprovisionnement)
            [
                'produit_id' => 1,
                'type_mouvement' => 'entree',
                'quantite' => 6,
                'stock_avant' => 24,
                'stock_apres' => 30,
                'motif' => 'Réapprovisionnement fournisseur Beauty Supplies BF',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'produit_id' => 6,
                'type_mouvement' => 'entree',
                'quantite' => 20,
                'stock_avant' => 49,
                'stock_apres' => 69,
                'motif' => 'Réapprovisionnement fournisseur Beauty Supplies BF',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subDays(4),
                'updated_at' => Carbon::now()->subDays(4),
            ],
            
            // Ajustements (corrections d'inventaire)
            [
                'produit_id' => 2,
                'type_mouvement' => 'ajustement',
                'quantite' => 2,
                'stock_avant' => 38,
                'stock_apres' => 40,
                'motif' => 'Correction inventaire - produits retrouvés en réserve',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'produit_id' => 9,
                'type_mouvement' => 'ajustement',
                'quantite' => 1,
                'stock_avant' => 34,
                'stock_apres' => 35,
                'motif' => 'Ajustement après inventaire',
                'vente_id' => null,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Sortie pour casse/perte
            [
                'produit_id' => 3,
                'type_mouvement' => 'ajustement',
                'quantite' => -1,
                'stock_avant' => 17,
                'stock_apres' => 16,
                'motif' => 'Bouteille cassée lors de la manipulation',
                'vente_id' => null,
                'user_id' => 2,
                'created_at' => Carbon::now()->subDays(6),
                'updated_at' => Carbon::now()->subDays(6),
            ],
        ];

        DB::table('mouvements_stock')->insert($mouvements);
    }
}