<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypePrestationSeeder extends Seeder
{
    public function run(): void
    {
        $typesPrestations = [
            [
                'nom' => 'Coupe Homme Simple',
                'description' => 'Coupe de cheveux classique pour homme',
                'duree_estimee_minutes' => 30,
                'prix_base' => 2000,
                'actif' => true,
                'ordre' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupe Homme + Dégradé',
                'description' => 'Coupe avec dégradé progressif',
                'duree_estimee_minutes' => 45,
                'prix_base' => 3000,
                'actif' => true,
                'ordre' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Taille de Barbe',
                'description' => 'Entretien et taille de la barbe',
                'duree_estimee_minutes' => 20,
                'prix_base' => 1500,
                'actif' => true,
                'ordre' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupe + Barbe',
                'description' => 'Service complet coupe et barbe',
                'duree_estimee_minutes' => 50,
                'prix_base' => 4000,
                'actif' => true,
                'ordre' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Rasage Traditionnel',
                'description' => 'Rasage complet au rasoir avec serviette chaude',
                'duree_estimee_minutes' => 40,
                'prix_base' => 3500,
                'actif' => true,
                'ordre' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupe Femme Courte',
                'description' => 'Coupe pour cheveux courts',
                'duree_estimee_minutes' => 45,
                'prix_base' => 3500,
                'actif' => true,
                'ordre' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupe Femme Mi-longue',
                'description' => 'Coupe pour cheveux mi-longs',
                'duree_estimee_minutes' => 60,
                'prix_base' => 5000,
                'actif' => true,
                'ordre' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tresses Africaines Simples',
                'description' => 'Tressage traditionnel de base',
                'duree_estimee_minutes' => 120,
                'prix_base' => 8000,
                'actif' => true,
                'ordre' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tresses avec Mèches',
                'description' => 'Tresses incorporant des mèches synthétiques',
                'duree_estimee_minutes' => 180,
                'prix_base' => 15000,
                'actif' => true,
                'ordre' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Défrisage',
                'description' => 'Défrisage chimique des cheveux',
                'duree_estimee_minutes' => 90,
                'prix_base' => 12000,
                'actif' => true,
                'ordre' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coloration Cheveux',
                'description' => 'Coloration complète ou mèches',
                'duree_estimee_minutes' => 120,
                'prix_base' => 18000,
                'actif' => true,
                'ordre' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Pose d\'Extensions',
                'description' => 'Installation d\'extensions naturelles',
                'duree_estimee_minutes' => 240,
                'prix_base' => 35000,
                'actif' => true,
                'ordre' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Tissage Complet',
                'description' => 'Pose de tissage avec tresses plaquées',
                'duree_estimee_minutes' => 180,
                'prix_base' => 25000,
                'actif' => true,
                'ordre' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Soin Capillaire Profond',
                'description' => 'Traitement nourrissant pour cheveux abîmés',
                'duree_estimee_minutes' => 60,
                'prix_base' => 7000,
                'actif' => true,
                'ordre' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coiffure Mariage/Événement',
                'description' => 'Coiffure élaborée pour occasions spéciales',
                'duree_estimee_minutes' => 150,
                'prix_base' => 30000,
                'actif' => true,
                'ordre' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Coupe Enfant',
                'description' => 'Coupe de cheveux pour enfants (-12 ans)',
                'duree_estimee_minutes' => 25,
                'prix_base' => 1500,
                'actif' => true,
                'ordre' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Lissage Brésilien',
                'description' => 'Traitement lissant à la kératine',
                'duree_estimee_minutes' => 180,
                'prix_base' => 40000,
                'actif' => true,
                'ordre' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Locks/Dreadlocks Entretien',
                'description' => 'Entretien et resserrage des locks',
                'duree_estimee_minutes' => 120,
                'prix_base' => 10000,
                'actif' => true,
                'ordre' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('types_prestations')->insert($typesPrestations);
    }
}